"""Add send_to field to announcements table

Revision ID: 0255e69aecaa
Revises: 
Create Date: 2026-03-23 10:02:23.606996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0255e69aecaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_announcement')
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.alter_column('club_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('send_to',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'club_members'"))

    with op.batch_alter_table('announcement_notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement_notification', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.alter_column('send_to',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'club_members'"))
        batch_op.alter_column('club_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('_alembic_tmp_announcement',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('club_id', sa.INTEGER(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=140), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('priority', sa.VARCHAR(length=16), nullable=False),
    sa.Column('pinned', sa.BOOLEAN(), nullable=True),
    sa.Column('expiry_date', sa.DATETIME(), nullable=True),
    sa.Column('attachment_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('attachment_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('resource_links', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('send_to', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
